### PR TITLE
Add support for RoundSync as a storage provider

### PR DESCRIPTION
**Pull request by Haxverse**
This PR is a copy of [the PR from seedvault-app/seedvault](https://github.com/seedvault-app/seedvault/pull/609).

I haven't tested the code, but I don't see a obvious reason this shouldn't work.

### CODE REVIEW

**Comment by fhilgers** [comment]
Whats the state? I would really love to have this feature. Currently backing up to local disk and syncing daily via RoundSync, but that requires a lot of storage space.

**Comment by thestinger** [comment]
It will be there when it's upgraded.

**Comment by fhilgers** [comment]
You mean the next grapheneos update, or android 15, or something completely different?

**Comment by thestinger** [comment]
When Seedvault is eventually updated, the changes made to it upstream will be included. Pull requests like this aren't going to be accepted. The reason we don't update it regularly is because of serious flaws with the development upstream leading to regular massive regressions. We can't trust the upstream code and people hostile towards us were allowed to become involved and take over large parts of the development.

**Comment by avineas** [comment]
> You mean the next grapheneos update, or android 15, or something completely different?

I might be dumb but i installed round-sync after seeing that grapheneos updated the seedvault version recently, enabled its document provider functionality, but i still didn't see RoundSync as an option for backup target. 

Did u manage to configure it? I assume the functionality is there now since that PR was merged to main repo in April 2024.

**Pull request closed without merging**
